### PR TITLE
Fix integer suffix parsing for non-decimal base

### LINKED ISSUE #599: Non-decimal ints with suffixes fail to parse
<table>
<thead>
<tr>
<th><code>Cargo.toml</code></th>
<th><code>src/main.rs</code></th>
</tr>
</thead>
<tbody>
<tr>
<td><pre><code>[package]
name = "rontest"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.12"</code></pre></td>
<td><pre><code>fn main() {
  assert_eq!(
    ron::from_str::<u32>("0xAu32"),
    Ok(0xAu32)
  );
}</code></pre></td>
</tr>
</tbody>
</table>

Result:
```
$ cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rontest`

thread 'main' (741474) panicked at src/main.rs:2:3:
assertion `left == right` failed
  left: Err(SpannedError { code: TrailingCharacters, span: Span { start: Position { line: 1, col: 4 }, end: Position { line: 1, col: 4 } } })
 right: Ok(10)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by juntyr**
Fixes #599 

* [x] I've included my change in `CHANGELOG.md`

### CODE REVIEW

File: src/parse.rs [hunk 1]
```diff
@@ -344,6 +337,13 @@ impl<'a> Parser<'a> {
         };
         let sign = if is_negative { -1 } else { 1 };
 
+        let base = match () {
+            () if self.consume_str("0b") => 2,
+            () if self.consume_str("0o") => 8,
+            () if self.consume_str("0x") => 16,
+            () => 10,
+        };
```
Comment (torkleyy) [inline src/parse.rs]: interesting pattern :D never seen this before

**Review by torkleyy — APPROVED** [review]
:shipit:
