### PR TITLE
Lossless `Value::Number` and allow +unsigned

### LINKED ISSUE #445: plus sign on unsigned integers
I don't see a reason why `+` should only be allowed on signed integers.

Currently this fails:
```rs
    assert_eq!(
        std::u64::MAX,
        from_str("+19").unwrap()
    );
```

### PR DESCRIPTION
**Pull request by juntyr**
This PR

* cleans up the `value` module a bit
* expands the `value::Number` enum to cover all possible number types losslessly
* merges the private `parser::AnyNum` type with `value::Number`
* fixes #445 by allowing `+unsigned` to parse as an unsigned integer

I see this as a small improvement towards a better `Value`. While it does touch a lot of tests, since `Number` is more explicit now and always chooses the smallest variant that fits (and `serde`'s `Deserialize` impls do the rest by upcasting again if necessary), more control could be given to the user with #241, if someone wants to implement that.

* [x] I've included my change in `CHANGELOG.md`

### CODE REVIEW

File: src/parse.rs [hunk 1]
```diff
@@ -858,6 +816,8 @@ impl<'a> Bytes<'a> {
     }
 
     pub fn unsigned_integer<T: Num>(&mut self) -> Result<T> {
```
Comment (juntyr) [inline src/parse.rs:818]: Since `signed_integer` and `unsigned_integer` are still exposed, they should get extra tests with strong typing
